apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Kro-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: add git
    targetRevision: HEAD
    path: KRO_DEMO/none-kro-app/example-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: team-x
  syncPolicy:
    automated:
      prune: false
      selfHeal: false