apiVersion: apps/v1
kind: Application
metadata:
  name: example-app
spec:
  application:
    name: mysql-db
    image: mysql:latest
    ingress:
      enabled: false
    db:
      type: postgres
      #replicas: 2